title: Din's Personal Website
email: din.ferizovic@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
name: 'Din Ferizović'
# Build settings
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
paginate: 1
sidebar_home_link:  true
sidebar_blog_link: '/blog'
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post